---

################################################################################
# Archivematica SRC Overrides/Vars
################################################################################

archivematica_src_am_version: "stable/1.15.x"
archivematica_src_ss_version: "stable/0.21.x"
archivematica_src_ss_gunicorn: "true"
archivematica_src_am_dashboard_gunicorn: "true"
install_rpm_repositories: "false"

# Databases

archivematica_src_am_db_host: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/database_dashboard.host', region='us-east-2', nested=true) }}"
archivematica_src_am_db_name: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/database_dashboard.dbname', region='us-east-2', nested=true) }}"
archivematica_src_am_db_user: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/database_dashboard.username', region='us-east-2', nested=true) }}"
archivematica_src_am_db_password: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/database_dashboard.password', region='us-east-2', nested=true) }}"
archivematica_src_ss_db_name: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/database_ss.dbname', region='us-east-2', nested=true) }}"
archivematica_src_ss_db_user: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/database_ss.username', region='us-east-2', nested=true) }}"
archivematica_src_ss_db_password: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/database_ss.password', region='us-east-2', nested=true) }}"

# Django

archivematica_src_django_allowed_hosts: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/django.allowed_hosts', region='us-east-2', nested=true) }}"
archivematica_src_am_django_secret_key: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/django.dashboard_secret_key', region='us-east-2', nested=true) }}"
archivematica_src_ss_django_secret_key: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/django.ss_secret_key', region='us-east-2', nested=true) }}"
archivematica_src_mcpserver_django_secret_key: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/django.mcpserver_secret_key', region='us-east-2', nested=true) }}"
archivematica_src_mcpclient_django_secret_key: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/django.mcpclient_secret_key', region='us-east-2', nested=true) }}"

# SMTP

archivematica_src_smtp_username: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/smtp.username', region='us-east-2', nested=true) }}"
archivematica_src_smtp_password: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/smtp.password', region='us-east-2', nested=true) }}"
archivematica_src_smtp_host: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/smtp.host', region='us-east-2', nested=true) }}"
archivematica_src_smtp_port: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/smtp.port', region='us-east-2', nested=true) }}"
archivematica_src_smtp_tls: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/smtp.use_tls', region='us-east-2', nested=true) }}"
archivematica_src_smtp_default_sender: "{{ lookup('amazon.aws.secretsmanager_secret', '/am/test/smtp.default_sender', region='us-east-2', nested=true) }}"

archivematica_src_am_create_db: "true"           
archivematica_src_am_create_dbuser: "true"       
archivematica_src_am_wait_local_mysql: "true"    

archivematica_src_reset_mcpdb: "false"           
archivematica_src_reset_shareddir: "false"
archivematica_src_reset_es: "false"              
archivematica_src_reset_am_all: "false"          
archivematica_src_reset_ss_db: "false"           

archivematica_src_configure_dashboard: "yes"
archivematica_src_configure_ss: "yes"
archivematica_src_configure_ss_url: "https://{{ lookup('amazon.aws.ssm_parameter', 'am/test/ss_dns_name', region='us-east-2') }}"
archivematica_src_configure_ss_api_key: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/ss.admin.api_key', region='us-east-2', nested=true) }}"
archivematica_src_configure_ss_user: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/ss.admin.username', region='us-east-2', nested=true) }}"
archivematica_src_configure_ss_password: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/ss.admin.password', region='us-east-2', nested=true) }}"
archivematica_src_configure_ss_email: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/ss.admin.email', region='us-east-2', nested=true) }}"
archivematica_src_configure_am_user: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/dashboard.admin.username', region='us-east-2', nested=true) }}"
archivematica_src_configure_am_password: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/dashboard.admin.username', region='us-east-2', nested=true) }}"
archivematica_src_configure_am_email: "{{ lookup('amazon.aws.secretsmanager_secret', 'am/test/dashboard.admin.email', region='us-east-2', nested=true) }}"
archivematica_src_configure_am_org_name: "{{ lookup('amazon.aws.ssm_parameter', '/am/test/dash_org_name', region='us-east-2') }}"
archivematica_src_configure_am_org_id: "{{ lookup('amazon.aws.ssm_parameter', '/am/test/dash_org_id', region='us-east-2') }}"

archivematica_src_ssl: "true"

# Environment Files

archivematica_src_am_mcpserver_environment:
  ARCHIVEMATICA_MCPSERVER_CLIENT_USER: "{{ archivematica_src_am_db_user }}"
  ARCHIVEMATICA_MCPSERVER_CLIENT_PASSWORD: "{{ archivematica_src_am_db_password }}"
  ARCHIVEMATICA_MCPSERVER_CLIENT_HOST: "{{ archivematica_src_am_db_host }}"
  ARCHIVEMATICA_MCPSERVER_CLIENT_DATABASE: "{{ archivematica_src_am_db_name }}"
  ARCHIVEMAITCA_MCPSERVER_EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  ARCHIVEMATICA_MCPSERVER_EMAIL_HOST: "{{ archivmematica_src_smtp_host }}"
  ARCHIVEMATICA_MCPSERVER_EMAIL_HOST_USER: "{{ archivematica_src_smtp_username }}"
  ARCHIVEMATICA_MCPSERVER_EMAIL_HOST_PASSWORD: "{{ archivematica_src_smtp_password }}"
  ARCHIVEMATICA_MCPSERVER_EMAIL_DEFAULT_FROM_EMAIL: "{{ archivematica_src_smtp_default_sender }}"
  ARCHIVEMATICA_MCPSERVER_MCPSERVER_DJANGO_SECRET_KEY: "{{ archivematica_src_mcpserver_django_secret_key }}"

archivematica_src_am_mcpclient_environment:
  ARCHIVEMATICA_MCPCLIENT_CLIENT_USER: "{{ archivematica_src_am_db_user }}"
  ARCHIVEMATICA_MCPCLIENT_CLIENT_PASSWORD: "{{ archivematica_src_am_db_password }}"
  ARCHIVEMATICA_MCPCLIENT_CLIENT_HOST: "{{ archivematica_src_am_db_host }}"
  ARCHIVEMATICA_MCPCLIENT_CLIENT_DATABASE: "{{ archivematica_src_am_db_name }}"
  ARCHIVEMAITCA_MCPCLIENT_EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  ARCHIVEMATICA_MCPCLIENT_EMAIL_HOST: "{{ archivmematica_src_smtp_host }}"
  ARCHIVEMATICA_MCPCLIENT_EMAIL_HOST_USER: "{{ archivematica_src_smtp_username }}"
  ARCHIVEMATICA_MCPCLIENT_EMAIL_HOST_PASSWORD: "{{ archivematica_src_smtp_password }}"
  ARCHIVEMATICA_MCPCLIENT_EMAIL_DEFAULT_FROM_EMAIL: "{{ archivematica_src_smtp_default_sender }}"
  ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_DJANGO_SECRET_KEY: "{{ archivematica_src_mcpclient_django_secret_key }}"
  ARCHIVEMATICA_MCPCLIENT_MCPCLIENT_CAPTURE_CLIENT_SCRIPT_OUTPUT: "true"


archivematica_src_am_dashboard_environment:
  ARCHIVEMATICA_DASHBOARD_CLIENT_DATABASE: "{{ archivematica_src_am_db_name }}"
  ARCHIVEMATICA_DASHBOARD_CLIENT_HOST: "{{ archivematica_src_am_db_host }}"
  ARCHIVEMATICA_DASHBOARD_CLIENT_USER: "{{ archivematica_src_am_db_user }}"
  ARCHIVEMATICA_DASHBOARD_CLIENT_PASSWORD: "{{ archivematica_src_am_db_password }}"
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_TIME_ZONE: "America/New_York"
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_ALLOWED_HOSTS: "{{ archivematica_src_django_allowed_hosts }}"
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_DJANGO_SECRET_KEY: "{{ archivematica_src_am_django_secret_key }}"
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_ELASTICSEARCH_TIMEOUT: "{{ lookup('amazon.aws.ssm_parameter', '/am/test/dash_es_timeout', region='us-east-2') }}"
  ARCHIVEMATICA_DASHBOARD_DASHBOARD_STORAGE_SERVICE_CLIENT_QUICK_TIMEOUT: "{{ lookup('amazon.aws.ssm_parameter', '/am/test/dash_es_quick_timeout', region='us-east-2') }}"
  ARCHIVEMATICA_DASHBOARD_EMAIL_HOST: "{{ archivematica_src_smtp_host }}"
  ARCHIVEMATICA_DASHBOARD_EMAIL_HOST_USER: "{{ archivematica_src_smtp_username }}"
  ARCHIVEMATICA_DASHBOARD_EMAIL_HOST_PASSWORD: "{{ archivematica_src_smtp_password }}"
  ARCHIVEMATICA_DASHBOARD_EMAIL_PORT: "{{ archivematica_src_smtp_port }}"
  ARCHIVEMATICA_DASHBOARD_EMAIL_USE_TLS: "{{ archivematica_src_smtp_tls }}"
  ARCHIVEMATICA_DASHBOARD_EMAIL_DEFAULT_FROM_EMAIL: "{{ archivematica_src_smtp_default_sender }}"
  ARCHIVEMATICA_DASHBOARD_SEARCH_ENABLED: "yes"

archivematica_src_ss_environment:
  DEFAULT_FROM_EMAIL: "{{ archivematica_src_smtp_default_sender }}"
  DJANGO_ALLOWED_HOSTS: "{{ archivematica_src_django_allowed_hosts }}"
  DJANGO_SETTINGS_MODULE: "storage_service.settings.production"
  DJANGO_SECRET_KEY: "{{ archivematica_src_ss_django_secret_key }}"
  EMAIL_HOST: "{{ archivematica_src_smtp_host }}"
  EMAIL_HOST_USER: "{{ archivematica_src_smtp_username }}"
  EMAIL_HOST_PASSWORD: "{{ archivematica_src_smtp_password }}"
  EMAIL_PORT: "{{ archivematica_src_smtp_port }}"
  EMAIL_USE_TLS: "{{ archivematica_src_smtp_tls }}"
  SECRET_KEY: "{{ archivematica_src_ss_django_secret_key }}"
  SS_DB_URL: "mysql://{{ archivematica_src_ss_db_user }}:{{ archivematica_src_ss_db_password }}@{{ archivematica_src_am_db_host }}:3306/{{ archivematica_src_ss_db_name }}"
  SS_DB_NAME: "{{ archivematica_src_ss_db_name }}"
  SS_DB_USER: "{{ archivematica_src_ss_db_user }}"
  SS_DB_PASSWORD: "{{ archivematica_src_ss_db_password }}"
  SS_DB_HOST: "{{ archivematica_src_am_db_host }}"

# elasticsearch role

elasticsearch_version: "6.5.4"
elasticsearch_apt_java_package: "openjdk-8-jre-headless"
elasticsearch_java_home: "/usr/lib/jvm/java-1.8.0-openjdk-amd64"
elasticsearch_heap_size: "1g"
elasticsearch_max_open_files: "65535"
elasticsearch_timezone: "UTC"
elasticsearch_node_max_local_storage_nodes: "1"
elasticsearch_index_mapper_dynamic: "true"
elasticsearch_memory_bootstrap_mlockall: "true"
elasticsearch_install_java: "true"
elasticsearch_thread_pools:
  - "thread_pool.bulk.size: 2"
  - "thread_pool.bulk.queue_size: 1000"
elasticsearch_network_http_max_content_lengtht: 1024mb
elasticsearch_discovery_zen_ping_multicast_enabled: "false"
elasticsearch_max_locked_memory: "unlimited"
elasticsearch_network_host: "127.0.0.1"

# fsulib.archivematica.external-db role

fsulib_ext_db_root_user: "{{ lookup('aws_ssm', '/am/test/db_root_user', region='us-east-2') }}"
fsulib_ext_db_root_password: "{{ lookup('aws_ssm', '/am/test/db_root_pass', region='us-east-2') }}"
mysql_databases:
  - name: "{{ archivematica_src_am_db_name }}"
    collation: "utf8_general_ci"
    encoding: "utf8"
    login_host: "{{ archivematica_src_am_db_host }}"
  - name: "{{ archivematica_src_ss_db_name }}"
    collation: "utf8_general_ci"
    encoding: "utf8"
    login_host: "{{ archivematica_src_am_db_host }}"

mysql_users:
  - name: "{{ archivematica_src_am_db_user }}"
    pass: "{{ archivematica_src_am_db_password }}"
    priv: "{{ archivematica_src_am_db_name }}.*:ALL,GRANT"
    login_host: "{{ archivematica_src_am_db_host }}"
    host: "%"
  - name: "{{ archivematica_src_ss_db_user }}"
    pass: "{{ archivematica_src_ss_db_password }}"
    priv: "{{ archivematica_src_ss_db_name }}.*:ALL,GRANT"
    login_host: "{{ archivematica_src_am_db_host }}"
    host: "%"
  - name: "{{ archivematica_src_db_dump_user }}"
    pass: "{{ archivematica_src_db_dump_password }}"
    priv: "{{ archivematica_src_am_db_name }}.*:SELECT,SHOW VIEW,TRIGGER,LOCK TABLES"
    login_host: "{{ archivematica_src_am_db_host }}"
    host: "%"
  - name: "{{ archivematica_src_db_dump_user }}"
    pass: "{{ archivematica_src_db_dump_password }}"
    append_privs: "true"
    priv: "{{ archivematica_src_ss_db_name }}.*:SELECT,SHOW VIEW,TRIGGER,LOCK TABLES" 
    login_host: "{{ archivematica_src_am_db_host }}"
    host: "%"

